name: Duplicate checker
on:
  push:
    branches:
        - master
    pull_request:
      branches:
        - master
        - develop
    paths:
      - 'pihole-google.txt'
jobs:
  update:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
      name: Python setup
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Check for duplicate lines
      run: |
        cd scripts
        pytest